# Generated by Django 5.2.7 on 2025-11-27 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_donante_instructor_servicio_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('equipo', models.CharField(help_text='Ej: Notebook HP, Impresora Epson...', max_length=100, verbose_name='Equipo / Dispositivo')),
                ('descripcion_problema', models.TextField(verbose_name='Descripción del Problema')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('en_proceso', 'En Reparación/Diagnóstico'), ('espera_repuesto', 'En Espera de Repuestos'), ('finalizado', 'Finalizado / Listo'), ('entregado', 'Entregado al Cliente')], default='pendiente', max_length=20)),
                ('notas_tecnicas', models.TextField(blank=True, help_text='Diagnóstico o notas internas del técnico', null=True)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_tecnicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
