# Generated by Django 5.2.7 on 2025-11-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_solicitudservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donante',
            name='equipo_donado',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='monto_donacion',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='tipo_donacion',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='cursos_creados',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='equipo_trabajado',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='estado_servicio',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='disponibilidad',
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='descripcion_problema',
            field=models.TextField(verbose_name='Problema Reportado'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='email_contacto',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='equipo',
            field=models.CharField(max_length=100, verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('falta_ingreso', 'Falta Ingreso (Solicitud Web)'), ('pendiente', 'Pendiente de Revisión'), ('en_proceso', 'En Reparación/Diagnóstico'), ('espera_repuesto', 'En Espera de Repuestos'), ('finalizado', 'Finalizado / Listo'), ('entregado', 'Entregado al Cliente')], default='falta_ingreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='notas_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('beneficiario', 'Beneficiario'), ('instructor', 'Instructor'), ('donante', 'Donante'), ('servicio', 'Servicio'), ('voluntario', 'Voluntario'), ('admin', 'Administrador')], max_length=15),
        ),
    ]
