# Generated by Django 5.2.5 on 2025-10-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0002_remove_usuario_comuna_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='curso',
            new_name='id_curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='estado',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id_beneficiario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
