# Generated by Django 5.2.5 on 2025-10-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_donacion', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_donacion', models.DateTimeField(auto_now_add=True)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('donacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donaciones.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario')),
                ('voluntario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.voluntario')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.equipo')),
            ],
        ),
    ]
