# Generated by Django 5.2.5 on 2025-10-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
    ]
