# Generated by Django 5.2.5 on 2025-10-15 04:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_sync_cantidad_field'),
        ('usuarios', '0002_remove_usuario_comuna_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='fecha_donacion',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='tipo_donacion',
        ),
        migrations.AddField(
            model_name='donacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donacion',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donacion',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donacion',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='usuarios.usuario'),
        ),
    ]
