# Generated by Django 5.2.7 on 2025-11-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_remove_donacion_fecha_donacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Donación'),
        ),
    ]
